<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib uri="http://displaytag.sf.net" prefix="display" %>

<h1>Upload text file generated by mini-beans for event ${event.name}</h1>

    <input type="hidden" value="${event.id}" name="id"/>
    <input type="hidden" value="${event.name}" name="name"/>

  <div class="rows">

      <div class="row">
          <div class="column w-33-percent">
          <c:forEach var="sale" items="${session.salesForUpload}" varStatus="rowCounter">
              ${sale.stockItem.id}
          </c:forEach>
         </div>

         <br/><br/>

      </div>

        <div class="row">
            <div class="column w-33-percent">
           <a href="/bookmarks/event/uploadSales" class="btn btn-primary">Upload Sales</a>
        </div>
    </div>

  </div>
